name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl:
          - "5.8"
          - "5.16"
          - "5.24"
          - "5.32"
    name: Perl ${{ matrix.perl }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: test
        run: |
          cpanm --installdeps .
          perl Build.PL
          ./Build
          ./Build test
